### ISSUE TITLE
几个错字

### ISSUE THREAD

**Issue by laoyuan** [cnDelbert/PracticalPHP#1]
http://php.code.kekou.de/Introducing_PHP/Advantages_of_PHP/output_control.html
HTML大麻 -> HTML代码

http://php.code.kekou.de/Introducing_PHP/Advantages_of_PHP/competing_languages.html
用Java谢 -> 用Java写

http://php.code.kekou.de/Introducing_PHP/How_PHP_is_written/index.html
PHP没事 -> PHP模式

http://php.code.kekou.de/Introducing_PHP/How_PHP_is_written/index.html
将会降到 -> 将会讲到

http://php.code.kekou.de/Introducing_PHP/further_reading.html
将了几句 -> 讲了几句

http://php.code.kekou.de/Simple_variables_and_operators/types_of_data.html
脊柱他们 -> 记住他们

http://php.code.kekou.de/Introducing_PHP/Advantages_of_PHP/performance.html
Perl商人 -> Perl贩子 或 Perl粉

http://php.code.kekou.de/Introducing_PHP/abnormal_script_termination.html
2.7 打不开

**Comment by cnDelbert** [comment]
已经改正。Thank you
