### ISSUE TITLE
几处错字什么的

### ISSUE THREAD

**Issue by laoyuan** [cnDelbert/PracticalPHP#2]
http://php.code.kekou.de/Introducing_PHP/abnormal_script_termination.html
代码太长，不能执行 -> 代码执行时间太长

http://php.code.kekou.de/Simple_variables_and_operators/Constants/pre-set_constants.html
新行的字符 -> 的换行符

http://php.code.kekou.de/Simple_variables_and_operators/Operators/the_ternary_operator.html
404

http://php.code.kekou.de/Functions/index.html
差不过 -> 差不多
某个功能缺失 -> 少了点什么

http://php.code.kekou.de/Functions/how_to_read_function_prototypes.html
在函数调用时必须使用原型 -> 在函数调用时必须像原型那样加上&
（本意应该是这样）

http://php.code.kekou.de/Functions/controlling_script_execution.html
逊于你讲 -> 允许你将

http://php.code.kekou.de/Functions/Working_with_date_and_time/reading_the_current_time.html
更近一步 -> 更进一步
得到日期的欸二天 -> 当前日期的第二天
文件洞 -> 文件中

**Comment by cnDelbert** [comment]
Done.
